#!/bin/sh

getopts "d" delete

MYSQL_LOG_DIR="/var/log/mysql"
if type systemctl >/dev/null 2>&1; then
	sudo systemctl stop mysql
else
	sudo service stop mysql
fi

if [ $delete = "d" ]; then
	sudo rm $MYSQL_LOG_DIR/mysql-slow.log
fi

if type systemctl >/dev/null 2>&1; then
	sudo systemctl start mysql
else
	sudo service start mysql
fi

#Nginx
NGINX_LOG_DIR="/var/log/nginx"
if [ $delete = "d" ]; then
	sudo rm $NGINX_LOG_DIR/access.log
fi

if type systemctl >/dev/null 2>&1; then
  sudo systemctl restart nginx
else
  sudo service nginx restart
fi

#pprof
PPROF_LOG_DIR="/home/isucon/pprof"
if type systemctl >/dev/null 2>&1; then
	sudo rm $PPROF_LOG_DIR/*.pb.gz
fi

sudo supervisorctl restart isucon_go

# sudo systemctl restart redis

